"""Seed data for the standard down-throat station."""

STANDARD_STATION = {
    "station_name": "下行咽喉标准站",
    "station_code": "DOWN_THROAT_STANDARD",
    "description": "用于阶段二联锁逻辑验收的标准下行咽喉站场。",
    "station_config": {
        "tracks": ["I", "II", "3", "4"],
        "throat": "down",
        "canvas": {"width": 1100, "height": 420, "viewBox": "0 0 1100 420"},
        "track_segments": [
            {"id": "seg-iag", "section": "IAG", "x1": 40, "y1": 210, "x2": 170, "y2": 210},
            {"id": "seg-1dg", "section": "1DG", "x1": 170, "y1": 210, "x2": 300, "y2": 210},
            {"id": "seg-3dg", "section": "3DG", "x1": 300, "y1": 210, "x2": 480, "y2": 210},
            {"id": "seg-5dg", "section": "5DG", "x1": 480, "y1": 210, "x2": 700, "y2": 210},
            {"id": "seg-7dg", "section": "7DG", "x1": 300, "y1": 210, "x2": 520, "y2": 130},
            {"id": "seg-9dg", "section": "9DG", "x1": 520, "y1": 130, "x2": 820, "y2": 130},
            {"id": "seg-2dg", "section": "2DG", "x1": 300, "y1": 210, "x2": 520, "y2": 290},
            {"id": "seg-4dg", "section": "4DG", "x1": 520, "y1": 290, "x2": 820, "y2": 290},
            {"id": "seg-6dg", "section": "6DG", "x1": 700, "y1": 210, "x2": 900, "y2": 210},
            {"id": "seg-8dg", "section": "8DG", "x1": 820, "y1": 130, "x2": 1010, "y2": 130},
            {"id": "seg-10dg", "section": "10DG", "x1": 820, "y1": 290, "x2": 1010, "y2": 290},
        ],
        "section_shapes": {
            "IAG": [{"x1": 40, "y1": 210, "x2": 170, "y2": 210}],
            "1DG": [{"x1": 170, "y1": 210, "x2": 300, "y2": 210}],
            "2DG": [{"x1": 300, "y1": 210, "x2": 520, "y2": 290}],
            "3DG": [{"x1": 300, "y1": 210, "x2": 480, "y2": 210}],
            "4DG": [{"x1": 520, "y1": 290, "x2": 820, "y2": 290}],
            "5DG": [{"x1": 480, "y1": 210, "x2": 700, "y2": 210}],
            "6DG": [{"x1": 700, "y1": 210, "x2": 900, "y2": 210}],
            "7DG": [{"x1": 300, "y1": 210, "x2": 520, "y2": 130}],
            "8DG": [{"x1": 820, "y1": 130, "x2": 1010, "y2": 130}],
            "9DG": [{"x1": 520, "y1": 130, "x2": 820, "y2": 130}],
            "10DG": [{"x1": 820, "y1": 290, "x2": 1010, "y2": 290}],
        },
        "switch_geometry": {
            "1#": {"x": 230, "y": 210, "normal": {"x2": 300, "y2": 210}, "reverse": {"x2": 300, "y2": 245}},
            "2#": {"x": 330, "y": 210, "normal": {"x2": 400, "y2": 210}, "reverse": {"x2": 400, "y2": 245}},
            "3#": {"x": 360, "y": 210, "normal": {"x2": 430, "y2": 210}, "reverse": {"x2": 430, "y2": 170}},
            "4#": {"x": 460, "y": 250, "normal": {"x2": 530, "y2": 275}, "reverse": {"x2": 530, "y2": 225}},
            "5#": {"x": 540, "y": 210, "normal": {"x2": 610, "y2": 210}, "reverse": {"x2": 610, "y2": 170}},
            "6#": {"x": 640, "y": 210, "normal": {"x2": 710, "y2": 210}, "reverse": {"x2": 710, "y2": 250}},
            "7#": {"x": 560, "y": 130, "normal": {"x2": 630, "y2": 130}, "reverse": {"x2": 630, "y2": 170}},
            "8#": {"x": 760, "y": 170, "normal": {"x2": 830, "y2": 145}, "reverse": {"x2": 830, "y2": 210}},
            "9#": {"x": 740, "y": 130, "normal": {"x2": 810, "y2": 130}, "reverse": {"x2": 810, "y2": 170}},
            "10#": {"x": 800, "y": 290, "normal": {"x2": 870, "y2": 290}, "reverse": {"x2": 870, "y2": 250}},
        },
        "labels": [
            {"text": "I道", "x": 820, "y": 198},
            {"text": "II道", "x": 920, "y": 198},
            {"text": "3道", "x": 900, "y": 118},
            {"text": "4道", "x": 900, "y": 278},
            {"text": "下行咽喉", "x": 500, "y": 50},
        ],
    },
}

STANDARD_SIGNALS = [
    {"signal_code": "X", "signal_type": "train", "position_x": 80, "position_y": 160, "direction": "right"},
    {"signal_code": "S", "signal_type": "train", "position_x": 920, "position_y": 160, "direction": "left"},
    *[
        {
            "signal_code": f"D{index}",
            "signal_type": "shunting",
            "position_x": 120 + index * 70,
            "position_y": 260 if index % 2 else 80,
            "direction": "right" if index % 2 else "left",
        }
        for index in range(1, 11)
    ],
]

STANDARD_SWITCHES = [
    {
        "switch_code": f"{index}#",
        "switch_type": "single",
        "normal_position": "normal",
        "position_x": 150 + index * 70,
        "position_y": 160,
    }
    for index in range(1, 11)
]

STANDARD_SECTIONS = [
    {"section_code": "IAG", "section_type": "approach"},
    *[{"section_code": f"{index}DG", "section_type": "track"} for index in range(1, 11)],
]

STANDARD_ROUTES = [
    {
        "route_name": "X至I道接车进路",
        "entry_signal": "X",
        "exit_signal": "I",
        "route_type": "receive",
        "switches_required": {"1#": "normal", "3#": "normal", "5#": "normal"},
        "sections_required": ["IAG", "1DG", "3DG", "5DG"],
        "hostile_routes": ["S至IAG发车进路", "D3至D7调车进路"],
    },
    {
        "route_name": "X至II道接车进路",
        "entry_signal": "X",
        "exit_signal": "II",
        "route_type": "receive",
        "switches_required": {"1#": "reverse", "3#": "normal", "7#": "normal"},
        "sections_required": ["IAG", "1DG", "3DG", "7DG"],
        "hostile_routes": ["S至IAG发车进路", "D1至D5调车进路"],
    },
    {
        "route_name": "X至3道接车进路",
        "entry_signal": "X",
        "exit_signal": "3",
        "route_type": "receive",
        "switches_required": {"1#": "reverse", "3#": "reverse", "5#": "normal"},
        "sections_required": ["IAG", "1DG", "3DG", "6DG"],
        "hostile_routes": ["D3至D7调车进路"],
    },
    {
        "route_name": "X至4道接车进路",
        "entry_signal": "X",
        "exit_signal": "4",
        "route_type": "receive",
        "switches_required": {"1#": "normal", "3#": "reverse", "9#": "normal"},
        "sections_required": ["IAG", "2DG", "4DG", "9DG"],
        "hostile_routes": ["D5至D9调车进路"],
    },
    {
        "route_name": "D1至I道调车进路",
        "entry_signal": "D1",
        "exit_signal": "I",
        "route_type": "shunting",
        "switches_required": {"1#": "normal", "2#": "normal"},
        "sections_required": ["1DG", "2DG"],
        "hostile_routes": ["X至II道接车进路"],
    },
    {
        "route_name": "D2至II道调车进路",
        "entry_signal": "D2",
        "exit_signal": "II",
        "route_type": "shunting",
        "switches_required": {"2#": "reverse", "4#": "normal"},
        "sections_required": ["2DG", "4DG"],
        "hostile_routes": ["S至II道发车进路"],
    },
    {
        "route_name": "S至IAG发车进路",
        "entry_signal": "S",
        "exit_signal": "IAG",
        "route_type": "departure",
        "switches_required": {"1#": "normal", "3#": "normal", "5#": "normal"},
        "sections_required": ["5DG", "3DG", "1DG", "IAG"],
        "hostile_routes": ["X至I道接车进路", "X至II道接车进路"],
    },
    {
        "route_name": "S至II道发车进路",
        "entry_signal": "S",
        "exit_signal": "II",
        "route_type": "departure",
        "switches_required": {"2#": "normal", "4#": "normal", "6#": "normal"},
        "sections_required": ["6DG", "4DG", "2DG"],
        "hostile_routes": ["D2至II道调车进路"],
    },
    {
        "route_name": "S至3道发车进路",
        "entry_signal": "S",
        "exit_signal": "3",
        "route_type": "departure",
        "switches_required": {"4#": "reverse", "6#": "normal", "8#": "normal"},
        "sections_required": ["8DG", "6DG", "4DG"],
        "hostile_routes": ["D6至D10调车进路"],
    },
    {
        "route_name": "S至4道发车进路",
        "entry_signal": "S",
        "exit_signal": "4",
        "route_type": "departure",
        "switches_required": {"6#": "reverse", "8#": "normal", "10#": "normal"},
        "sections_required": ["10DG", "8DG", "6DG"],
        "hostile_routes": ["D5至D9调车进路"],
    },
    {
        "route_name": "D3至D7调车进路",
        "entry_signal": "D3",
        "exit_signal": "D7",
        "route_type": "shunting",
        "switches_required": {"3#": "normal", "5#": "reverse"},
        "sections_required": ["3DG", "5DG"],
        "hostile_routes": ["X至I道接车进路", "X至3道接车进路"],
    },
    {
        "route_name": "D4至D8调车进路",
        "entry_signal": "D4",
        "exit_signal": "D8",
        "route_type": "shunting",
        "switches_required": {"4#": "normal", "6#": "reverse"},
        "sections_required": ["4DG", "6DG"],
        "hostile_routes": ["S至3道发车进路"],
    },
    {
        "route_name": "D5至D9调车进路",
        "entry_signal": "D5",
        "exit_signal": "D9",
        "route_type": "shunting",
        "switches_required": {"5#": "normal", "7#": "reverse", "9#": "normal"},
        "sections_required": ["5DG", "7DG", "9DG"],
        "hostile_routes": ["X至4道接车进路", "S至4道发车进路"],
    },
    {
        "route_name": "D6至D10调车进路",
        "entry_signal": "D6",
        "exit_signal": "D10",
        "route_type": "shunting",
        "switches_required": {"6#": "normal", "8#": "reverse", "10#": "normal"},
        "sections_required": ["6DG", "8DG", "10DG"],
        "hostile_routes": ["S至3道发车进路"],
    },
    {
        "route_name": "D7至D3调车进路",
        "entry_signal": "D7",
        "exit_signal": "D3",
        "route_type": "shunting",
        "switches_required": {"5#": "reverse", "3#": "normal"},
        "sections_required": ["5DG", "3DG"],
        "hostile_routes": ["X至I道接车进路"],
    },
    {
        "route_name": "D8至D4调车进路",
        "entry_signal": "D8",
        "exit_signal": "D4",
        "route_type": "shunting",
        "switches_required": {"6#": "reverse", "4#": "normal"},
        "sections_required": ["6DG", "4DG"],
        "hostile_routes": ["S至II道发车进路"],
    },
    {
        "route_name": "D9至D5调车进路",
        "entry_signal": "D9",
        "exit_signal": "D5",
        "route_type": "shunting",
        "switches_required": {"9#": "normal", "7#": "reverse", "5#": "normal"},
        "sections_required": ["9DG", "7DG", "5DG"],
        "hostile_routes": ["S至4道发车进路"],
    },
    {
        "route_name": "D10至D6调车进路",
        "entry_signal": "D10",
        "exit_signal": "D6",
        "route_type": "shunting",
        "switches_required": {"10#": "normal", "8#": "reverse", "6#": "normal"},
        "sections_required": ["10DG", "8DG", "6DG"],
        "hostile_routes": ["S至3道发车进路"],
    },
    {
        "route_name": "D1至D3调车进路",
        "entry_signal": "D1",
        "exit_signal": "D3",
        "route_type": "shunting",
        "switches_required": {"1#": "normal", "3#": "normal"},
        "sections_required": ["1DG", "3DG"],
        "hostile_routes": ["X至II道接车进路"],
    },
    {
        "route_name": "D2至D4调车进路",
        "entry_signal": "D2",
        "exit_signal": "D4",
        "route_type": "shunting",
        "switches_required": {"2#": "normal", "4#": "normal"},
        "sections_required": ["2DG", "4DG"],
        "hostile_routes": ["S至II道发车进路"],
    },
    {
        "route_name": "D3至D5调车进路",
        "entry_signal": "D3",
        "exit_signal": "D5",
        "route_type": "shunting",
        "switches_required": {"3#": "reverse", "5#": "normal"},
        "sections_required": ["3DG", "5DG"],
        "hostile_routes": ["X至I道接车进路"],
    },
    {
        "route_name": "D4至D6调车进路",
        "entry_signal": "D4",
        "exit_signal": "D6",
        "route_type": "shunting",
        "switches_required": {"4#": "reverse", "6#": "normal"},
        "sections_required": ["4DG", "6DG"],
        "hostile_routes": ["S至3道发车进路"],
    },
]
