import request from '@/utils/request'
const base='/management'
export const getManagementMetadata=()=>request.get(base+'/metadata')
export const getManagementOverview=()=>request.get(base+'/overview')
export const listManagedQuestions=params=>request.get(base+'/questions',{params})
export const getManagedQuestion=id=>request.get(`${base}/questions/${id}`)
export const createManagedQuestion=content=>request.post(base+'/questions',{content})
export const saveQuestionDraft=(id,content,revision)=>request.put(`${base}/questions/${id}/draft`,{content,revision})
export const publishQuestion=(id,revision,note)=>request.post(`${base}/questions/${id}/publish`,{revision,note})
export const setQuestionStatus=(id,revision,status)=>request.post(`${base}/questions/${id}/status`,{revision,status})
export const bulkQuestionStatus=(items,status)=>request.post(base+'/questions/bulk-status',{items,status})
export const cloneQuestion=id=>request.post(`${base}/questions/${id}/clone`)
export const getQuestionVersions=id=>request.get(`${base}/questions/${id}/versions`)
export const restoreQuestionVersion=(id,version,revision)=>request.post(`${base}/questions/${id}/versions/${version}/restore`,{revision})
export const previewManagedQuestion=(content,answers)=>request.post(base+'/preview',{content,...(answers===undefined?{}:{answers})})
export const listReviews=params=>request.get(base+'/reviews',{params})
export const getReview=id=>request.get(`${base}/reviews/${id}`)
export const saveReviewDraft=(id,content)=>request.put(`${base}/reviews/${id}/draft`,{content})
export const submitGrade=(id,body)=>request.post(`${base}/reviews/${id}/grade`,body)
export const exportGrades=params=>request.get(base+'/reviews/export',{params,responseType:'blob'})
export const getFeedbackSnippets=()=>request.get(base+'/snippets')
export const addFeedbackSnippet=text=>request.post(base+'/snippets',{text})
export const deleteFeedbackSnippet=id=>request.delete(`${base}/snippets/${id}`)
