<template>
  <div class="question-bank" v-loading="busy">
    <header class="manage-heading"><div><span class="overline">教学内容工作台</span><h1>题库工作台</h1><p>整理题目、设计评分规则，预览后发布给学生。</p></div><div class="heading-actions"><router-link class="primary-button" to="/admin/questions/new">＋ 自行出题</router-link></div></header>
    <section class="overview-grid"><article><span>全部题目</span><strong>{{ overview.questions??'—' }}</strong></article><article><span>学生可见</span><strong>{{ overview.published??'—' }}</strong></article><article><span>待完善草稿</span><strong>{{ overview.drafts??'—' }}</strong></article><article><span>待评作答</span><strong>{{ overview.pending??'—' }}</strong><router-link to="/admin/grading">去批阅 →</router-link></article></section>
    <section class="bank-panel">
      <div class="filters"><el-input v-model="filters.search" placeholder="搜索题目标题" clearable @keyup.enter="refresh" @clear="refresh" aria-label="搜索题目"/><el-select v-model="filters.topic" clearable placeholder="全部专题" aria-label="按专题筛选" @change="refresh"><el-option v-for="t in topics" :key="t.id" :value="t.id" :label="t.title"/></el-select><el-select v-model="filters.status" aria-label="按状态筛选" @change="refresh"><el-option label="全部状态" value="all"/><el-option label="已发布" value="published"/><el-option label="有草稿" value="draft"/><el-option label="已停用" value="archived"/></el-select><el-button @click="refresh">查找</el-button></div>
      <div class="selection-bar"><span>{{ selected.length?`已选择 ${selected.length} 题`:`共 ${total} 道题目` }}</span><template v-if="selected.length"><button @click="bulk('published')">批量启用已发布版本</button><button @click="bulk('archived')">批量停用</button></template><small v-else>已发布题目可继续编辑草稿，学生会看到最近一次发布的版本。</small></div>
      <el-table :data="items" row-key="id" @selection-change="value=>selected=value" empty-text="没有符合条件的题目，可新建或复制已有题目。">
        <el-table-column type="selection" width="52"/>
        <el-table-column label="题目" min-width="290"><template #default="{row}"><router-link class="question-title" :to="`/admin/questions/${row.id}`"><Notation :text="row.title"/></router-link><p class="row-meta">{{ row.topic_title }} · {{ row.field_count }} 个作答栏 · {{ row.total_points }} 分</p><span v-for="tag in row.tags" :key="tag" class="tag">{{ tag }}</span></template></el-table-column>
        <el-table-column label="状态 / 版本" width="170"><template #default="{row}"><span :class="['status',row.status]">{{ labels[row.status] }}</span><small v-if="row.has_draft&&row.status!=='draft'" class="draft-hint">有未发布修改</small><p class="row-meta">{{ row.published_version?`已发布 v${row.published_version}`:'尚未发布' }}</p></template></el-table-column>
        <el-table-column label="最近更新" width="160"><template #default="{row}"><small>{{ formatDate(row.updated_at) }}</small></template></el-table-column>
        <el-table-column label="操作" width="270"><template #default="{row}"><div class="row-actions"><router-link :to="`/admin/questions/${row.id}`">编辑</router-link><button @click="copy(row)">复制出题</button><button v-if="row.status==='published'" @click="setStatus(row,'archived')">停用</button><button v-else-if="row.published_version" @click="setStatus(row,'published')">启用</button></div></template></el-table-column>
      </el-table>
      <div class="pagination"><el-pagination v-model:current-page="page" :page-size="20" :total="total" layout="prev, pager, next, total" @current-change="load"/></div>
    </section>
  </div>
</template>

<script setup>
import { onMounted,reactive,ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage,ElMessageBox } from 'element-plus'
import Notation from '@/components/RailwayNotation.vue'
import {getManagementMetadata,getManagementOverview,listManagedQuestions,cloneQuestion,setQuestionStatus,bulkQuestionStatus} from '@/api/management'
const router=useRouter(),busy=ref(false),items=ref([]),selected=ref([]),total=ref(0),page=ref(1),overview=ref({}),topics=ref([])
const filters=reactive({search:'',topic:null,status:'all'}),labels={published:'已发布',draft:'草稿',archived:'已停用'}
let serial=0
function formatDate(value){return value?new Date(value.endsWith('Z')?value:value+'Z').toLocaleString('zh-CN'):'—'}
async function load(){const current=++serial;busy.value=true;try{const [data,stats]=await Promise.all([listManagedQuestions({...filters,topic:filters.topic||undefined,page:page.value}),getManagementOverview()]);if(current!==serial)return;items.value=data.items;total.value=data.total;overview.value=stats;selected.value=[]}finally{if(current===serial)busy.value=false}}
function refresh(){page.value=1;load()}
async function copy(row){busy.value=true;try{const q=await cloneQuestion(row.id);await router.push(`/admin/questions/${q.id}`)}finally{busy.value=false}}
async function setStatus(row,status){try{await ElMessageBox.confirm(status==='archived'?`停用“${row.title}”后学生不能开始新作答，历史记录保留。`:'启用最近一次已发布版本；未发布草稿仍保留。','调整题目可见状态',{confirmButtonText:'确认',cancelButtonText:'取消'})}catch{return}busy.value=true;try{await setQuestionStatus(row.id,row.revision,status);await load();ElMessage.success('题目状态已更新')}finally{busy.value=false}}
async function bulk(status){try{await ElMessageBox.confirm(`对已选 ${selected.value.length} 道题执行${status==='published'?'启用已发布版本':'停用'}？`,'批量调整',{confirmButtonText:'确认',cancelButtonText:'取消'})}catch{return}busy.value=true;try{await bulkQuestionStatus(selected.value.map(q=>({id:q.id,revision:q.revision})),status);await load();ElMessage.success('批量更新成功')}finally{busy.value=false}}
onMounted(async()=>{topics.value=(await getManagementMetadata()).topics;await load()})
</script>

<style scoped>
.manage-heading{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:25px}.overline{font-size:var(--ui-text-meta);letter-spacing:2px;color:#4382a0}.manage-heading h1{font-size:30px;margin:10px 0}.manage-heading p{color:#586f82;line-height:1.8;margin:0;font-size:var(--ui-text-base)}.heading-actions{display:flex;gap:10px;align-items:center}.primary-button,.quiet-button{padding:12px 18px;border-radius:6px;font-size:var(--ui-text-base);white-space:nowrap}.primary-button{color:white;background:#0075b7}.quiet-button{background:white;border:1px solid #d8e4ee;color:#507890}.overview-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px;margin:0 0 22px}.overview-grid article{padding:20px 24px;background:white;border:1px solid #dce7ef;border-radius:8px;position:relative}.overview-grid span{font-size:var(--ui-text-base);color:#586f82}.overview-grid strong{display:block;font:34px Georgia;color:#2a5978;margin-top:10px}.overview-grid a{position:absolute;right:20px;bottom:20px;font-size:var(--ui-text-base)}.bank-panel{background:white;border:1px solid #dce7ef;border-radius:9px;padding:22px}.filters{display:flex;gap:10px;align-items:center}.filters>.el-input{flex:1;min-width:140px}.filters>.el-select{width:170px}.selection-bar{display:flex;gap:14px;align-items:center;min-height:58px;font-size:var(--ui-text-base);color:#66869c}.selection-bar small{margin-left:auto;color:#586f82;line-height:1.6}.selection-bar button,.row-actions button{background:none;border:0;padding:0;color:#0075b7;cursor:pointer;font:inherit}.question-title{font-size:var(--ui-text-body);font-weight:500;color:#285b7b}.row-meta{font-size:var(--ui-text-meta);color:#586f82;margin:7px 0}.tag{display:inline-block;background:#edf5fb;color:#6289a2;font-size:var(--ui-text-sm);padding:2px 6px;border-radius:3px;margin:0 5px 3px 0}.status{font-size:var(--ui-text-meta);border-radius:4px;padding:4px 8px}.status.published{color:#30836c;background:#eaf7f1}.status.draft{color:#a57934;background:#fff6e7}.status.archived{color:#586f82;background:#eef2f6}.draft-hint{display:block;color:#aa864c;font-size:var(--ui-text-sm);margin-top:8px}.row-actions{display:flex;gap:14px;font-size:var(--ui-text-base)}.pagination{margin-top:22px;display:flex;justify-content:flex-end}@media(max-width:900px){.manage-heading{align-items:flex-start;flex-direction:column}.filters{flex-wrap:wrap}.filters>.el-input{flex-basis:100%}.overview-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.selection-bar{flex-wrap:wrap;padding:10px 0}.selection-bar small{margin-left:0}.bank-panel{padding:15px}.overview-grid article{padding:16px}.heading-actions{flex-wrap:wrap}}
</style>
